// vite-svelte/src/App.svelte
<script lang="ts">
  import { umi } from './umi'
  import type { BlockhashWithExpiryBlockHeight } from '@metaplex-foundation/umi'

  let blockhash: BlockhashWithExpiryBlockHeight | null = null

  const onClick = () => {
    umi.rpc.getLatestBlockhash().then((res) => {
      console.log(res)
      blockhash = res
    })
  }
</script>

<main>
  <button on:click={onClick}>Get Latest Blockhash</button>
  <pre>{blockhash ? JSON.stringify(blockhash, null, 2) : ''}</pre>
</main>

// vite-vue/src/App.vue
<script setup lang="ts">
import { umi } from './umi.ts'
import type { BlockhashWithExpiryBlockHeight } from '@metaplex-foundation/umi'
import { ref } from 'vue'

const blockhash = ref<BlockhashWithExpiryBlockHeight | null>(null)

function onClick() {
  umi.rpc.getLatestBlockhash().then((res) => {
    console.log(res)
    blockhash.value = res
  })
}
</script>

<template>
  <div>
    <button @click="onClick">Get Latest Blockhash</button>
    <pre>{{ blockhash ? JSON.stringify(blockhash, null, 2) : '' }}</pre>
  </div>
</template>
