// vite-react/src/App.tsx
import { useState } from 'react'

import { umi } from './umi.ts'
import { BlockhashWithExpiryBlockHeight } from '@metaplex-foundation/umi'

function App() {
  const [blockhash, setBlockhash] = useState<BlockhashWithExpiryBlockHeight | null>(null)

  async function onClick() {
    umi.rpc.getLatestBlockhash().then((res) => {
      console.log(res)
      setBlockhash(res)
    })
  }

  return (
    <div>
      <button onClick={onClick}>Get Latest Blockhash</button>
      <pre>{blockhash ? JSON.stringify(blockhash, null, 2) : ''}</pre>
    </div>
  )
}

export default App

// vite-svelte/src/App.svelte
<script lang="ts">
  import { umi } from './umi'
  import type { BlockhashWithExpiryBlockHeight } from '@metaplex-foundation/umi'

  let blockhash: BlockhashWithExpiryBlockHeight | null = null

  const onClick = () => {
    umi.rpc.getLatestBlockhash().then((res) => {
      console.log(res)
      blockhash = res
    })
  }
</script>

<main>
  <button on:click={onClick}>Get Latest Blockhash</button>
  <pre>{blockhash ? JSON.stringify(blockhash, null, 2) : ''}</pre>
</main>
